### PR TITLE
fix token conflict by passing sessionId into generateToken

### PR DESCRIPTION
**Pull request by zjb421**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/Opentok-Java-SDK/pull/115" target="_blank">ReviewNinja

**Comment by msach22** [comment]
Closing this PR because it's quite outdated. Please re-open if you have any questions!

**Comment by zjb421** [comment]
@msach22 why you closing it bro! @aoberoi

**Comment by aoberoi** [comment]
@msach22 so, should I ban @zjb421 or will you? 🤣

**Comment by zjb421** [comment]
Last evidence that i used to work really hard....

**Pull request closed without merging**
