### PR TITLE
Prefer JSON format response while creating an Opentok session

### PR DESCRIPTION
**Pull request by juandebravo**
We're aiming to use this library in the near future for our integration with Opentok. While checking the code I saw that this SDK is still using the deprecated XML format for generating a session.

This PR includes a suggestion for preferring JSON format instead of XML.

thanks!

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/Opentok-Java-SDK/pull/119" target="_blank">ReviewNinja

**Comment by ggarber** [comment]
retest this please

**Comment by juandebravo** [comment]
test this please

**Comment by ggarber** [comment]
retest this please

**Pull request merged**
