### PR TITLE
Added support for describing archive layouts for composed archives, addresses #131

### PR DESCRIPTION
**Pull request by tonycapone**
Hello. This implements support for [controlling layouts](https://tokbox.com/developer/guides/archiving/layout-control.html)  in composed archives in the start-archive call. 

Addresses issue #131 

I look forward to any feedback you have on this. Thanks!

### CODE REVIEW

**Comment by aullman** [comment]
Thanks for your contribution @tonycapone! Would you be able to add the license header to the ArchiveLayout.java file? It looks like that is what the CI is complaining about...

**Comment by aiham** [comment]
@tonycapone Can you also please base your PR off the `dev` branch instead of `master`? Thanks

**Comment by aiham** [comment]
@tonycapone Nevermind, I've done it.

**Comment by tonycapone** [comment]
Hi @aiham, I added the license header. Thanks!

**Pull request merged**
