### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by SMadani**
This is a security patch release which updates the dependency versions, including WireMock to v2.35.0 (which only affects tests). Functionality and documentation is unchanged. The copyright year has also been updated to make license check pass.

### CODE REVIEW

**Review by dragonmantank — CHANGES_REQUESTED** [review]
SHoot, I clicked "view file" too many times and lost which one it was, but one of the classes changed the properties to `final`. Since that's a restrictive change, it would be a BC change (as opposed to being `final` and moving to something more open). So technically this cannot be a patch release.

If that part is reverted then it's all good for the patched version assigned

**Comment by SMadani** [comment]
> SHoot, I clicked "view file" too many times and lost which one it was, but one of the classes changed the properties to `final`. Since that's a restrictive change, it would be a BC change (as opposed to being `final` and moving to something more open). So technically this cannot be a patch release.
> 
> If that part is reverted then it's all good for the patched version assigned

Thanks for looking this over. In Java, if something is private, it is not exposed outside of the class (at least not without reflection, which is harder in more recent versions anyway). Thus any changes to a private memeber are not breaking changes as they are invisible to a user. I'm guessing you're referring to API key & secret in `OpenTok.java`, which is only ever set in the constructor anyway.

**Review by dragonmantank — APPROVED** [review]

**Comment by dragonmantank** [comment]
That's what I get for not re-finding it. I thought I had read it as public final, but you are right, since it's private already not much is actually changing.

**Comment by SMadani** [comment]
Thanks :) Now just got to deal with the codecov target

**Pull request merged**
